-- =====================================================================
-- 01b_produtos — 258 produtos e as fichas vazias
-- Cole no SQL Editor do Supabase e rode. Ordem: 01a, 01b, 01c, 01d.
-- =====================================================================
set search_path = ops, public;
begin;

-- ---------- produtos ----------
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('1CBWB','Coffee 250g - White Edition','Shop',coalesce(58.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('1CCB','Coado Chemex   - Black','Methods',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('1CCK','Coado Chemex   - Kraft','Methods',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('1CCW','Coado Chemex   - White','Methods',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('1DCH','Cafe Coado - White','Methods',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('1DCHB','Cafe Coado - Black','Methods',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('1DCHK','Cafe Coado - Kraft','Methods',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('1DRR','V60 Dripper','Shop',coalesce(145.0,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('1FC','Flat Caramel','Signature',coalesce(15.5,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('1IC','Iced Vanilla','Signature',coalesce(16.5,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('1ICHAI','Chai Iced Latte','Purists',coalesce(17.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('1PB','Pure Black (Double Shot)','Purists',coalesce(10.5,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('1PBDRGAPP','Draguee Pure Black','Purists',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('1TB','Totebags','Shop',coalesce(55.0,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('2AM','Americano','Purists',coalesce(11.5,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('2CBKE','Coffee 250g - Kraft Edition','Shop',coalesce(69.0,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('2CIL','Tonka Iced Latte','Signature',coalesce(17.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('2DCCB','Cafe Coado Gelado - Black','Methods',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('2DCCK','Cafe Coado Gelado - Kraft','Methods',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('2FOOD2','Croissant','Food',coalesce(11.5,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('2PF','Paper Filter','Shop',coalesce(28.0,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('2SC','Salted Caramel','Signature',coalesce(18.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('2VLT','Vanilla Latte','Signature',coalesce(14.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('2WMK','With milk (Pure Black)','Personalization',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('3BG','Black Ginger','Signature',coalesce(18.5,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('3CBBE','Coffee 250g - Black Edition','Shop',coalesce(79.0,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('3DCMB','Cafe Coado Gelado + leite - Black','Methods',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('3DCMK','Cafe Coado Gelado + leite- Kraft','Methods',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('3FOOD3','Pain au Chocolat','Food',coalesce(13.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('3MC','Mad Mocha','Signature',coalesce(14.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('3TBB','Tumbler 360ml','Shop',coalesce(89.0,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('3TCH','Cookie Triple Chocolate','Personalization',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('4CB1','Coffee 1kg White','Shop',coalesce(159.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('4MIL','Matcha Iced Latte','Purists',coalesce(16.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('4TBS','Tumbler 240ml','Shop',coalesce(75.0,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('4TW','True White','Purists',coalesce(13.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('4UC','Urban Chocolat','Signature',coalesce(12.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('5CM','Chocold Mint','Signature',coalesce(17.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('5IL','Iced Latte','Purists',coalesce(14.5,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('5MC','Matcha Latte','Purists',coalesce(15.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('5MUG','Mug','Shop',coalesce(55.0,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('6BCB','Cold Brew Bottle','Shop',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('6CIG','Chai Iced Ginger','Signature',coalesce(18.5,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('6CM','Chai Latte','Purists',coalesce(15.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('6ICB','Iced Black','Purists',coalesce(12.5,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('7IC','Matcha Iced Mint','Signature',coalesce(18.5,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('7MVT','Matcha Vanilla Latte','Signature',coalesce(16.5,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('8BOLO8','Cake','Food',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('8DIC','Dark Iced Latte','Limited Time',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('8DLA','Dark Latte','Limited Time',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('8EXPA','Aram','Methods',coalesce(14.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('8EXPADAPP','Aram','Methods',coalesce(14.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('8MIT','Matcha Tonka Iced Latte','Signature',coalesce(17.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('8MT','Matcha Tonka Latte','Signature',coalesce(16.5,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('9CL','Tonka Latte','Signature',coalesce(14.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('9COOK9','Cookies','Food',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('9IMT','Ichigo Matcha','Signature',coalesce(18.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('ACX1','Água na Caixa 500ml','Other beverages',coalesce(9.5,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('AFCA','Affogato Chai','Desserts',coalesce(19.5,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('AFCF','Affogato Coffee','Desserts',coalesce(20.6,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('AFMC','Affogato Mocca','Desserts',coalesce(20.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('AFMT','Affogato Matcha','Desserts',coalesce(20.5,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('APMALAAPP','Apple Maple Latte','Limited Time',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('BABYCCAPP','Milknilla','Signature',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('BBAN','Banana Loaf','Personalization',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('BISN','Biscoito de Natal','Shop',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('BLALATAPP','Black Iced Latte','Limited Time',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('BLIM','Lemon Loaf','Personalization',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('BORG','Orange Loaf','Personalization',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('BR3','Misto com Tomate Cereja','Food',coalesce(18.5,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('BRCHAP','Chocolate Brioche','Personalization',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('BRGS','Brioche Gouda & Salsa','Personalization',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('BRICE','Brownie com sorvete','Desserts',coalesce(21.5,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('BRIG10','Brigadeiro','Food',coalesce(5.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('BRIOP','Brioches','Food',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('BRO13','Brownie','Food',coalesce(9.5,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('BRTSM','Brioche Tomate Seco e Manjericão','Personalization',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('BTKAPP','Bostok','Food',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('BUNCARAPP','Bun Caramelo','Food',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('BUNCHOAPP','Bun Chocolate','Food',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('BacCri','Bacon Crispy','Promo',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('BlendHalloween','Blend de Halloween','Limited Time',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('Brunch Brie e copa lombo - Stand By','Brie e copa lombo - Stand By','Brunch',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('C1FCCKTR','Flat Caramel + Cookie Traditional','Promo',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('C1IC3FOOD3','Iced Vanilla + Pain au Chocolat','Promo',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('C1ICCKTR','Iced Vanilla + Cookie Traditional','Promo',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('C1PBBRIG10','Pure Black + Brigadeiro','Promo',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('C2PM2FOOD2','Americano + Croissant','Promo',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('C2PMBRO13','Americano + Brownie','Promo',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('C2SCSLTC','Salted Caramel + Cookie Salted Caramel','Promo',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('C3BG2FOOD2','Black Ginger + Croissant','Promo',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('C3MCBLIM','Mad Mocha + Lemon Loaf','Promo',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('C3MCCKTR','Mad Mocha + Cookie Traditional','Promo',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('C4MILCKMC','Matcha Iced Latte + Cookie Macadamia','Promo',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('C4TWPDQ11','True White + Pao de queijo','Promo',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('C5CM3FOOD3','Chocold Mint + Pain au Chocolat','Promo',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('C5ILBRIG10','Iced Latte + Brigadeiro','Promo',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('C5ILPDQ11','Iced Latte + Pão de queijo','Promo',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('C5MCCKMC','Matcha Latte + Cookie Macadamia','Promo',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('C6ICBBRO13','Verificar formação de preço','Promo',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('CAFLATAPP','Caffe Latte','Purists',coalesce(12.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('CAKBANAPP','Banana Loaf','Food',coalesce(10.5,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('CAKDAYAPP','Cake Day','Food',coalesce(19.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('CAKLEMAPP','Lemon Loaf','Food',coalesce(9.5,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('CAKORAAPP','Orange Loaf','Food',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('CAPUCCAPP','Capuccino','Purists',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('CARLATAPP','Caramel Latte','Signature',coalesce(14.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('CF1','Fellow Kettle','Shop',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('CH4G','Chocolate 40g','Food',coalesce(13.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('CH8G','Chocolate 8g','Food',coalesce(3.5,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('CHECROAPP','Croissant com Queijo','Food',coalesce(18.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('CHIPUDAPP','Chia Pudding','Brunch',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('CHONATAP','Biscoito de Natal Chocolate','Limited Time',coalesce(49.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('CKICE','Cake with Ice Cream','Desserts',coalesce(20.5,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('CKMC','Cookie Macadamia','Personalization',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('CKOICE','Orange Cake with Ice Cream','Personalization',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('CKPS','Cookie Pumpkin Spices','Personalization',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('CKTR','Cookie Traditional','Personalization',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('COLORGAPP','Orange Juice 250ml','Other beverages',coalesce(13.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('COLYELAPP','Yellow Juice 250ml','Other beverages',coalesce(13.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('COOCARAPP','Salted Caramel Cookie','Sweets',coalesce(9.5,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('COOCHOAPP','Cookie Triple Chocolate','Sweets',coalesce(8.5,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('COOMACAPP','Macadâmia Cookie','Sweets',coalesce(9.5,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('COOMATAPP','Cookie Matcha & White Chocolate','Sweets',coalesce(9.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('COOTRAAPP','Cookie Traditional','Sweets',coalesce(7.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('CRMUJAAPP','Croissant Recheado com Muçarela e Jamón','Food',coalesce(45.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('CROGELAPP','Croissant com Geléia','Food',coalesce(18.5,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('CROMATAPP','Croissant com Creme de Matcha','Food',coalesce(18.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('CROPORAPP','Croissant com Queijo e Copa','Food',coalesce(24.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('CRRIMEAPP','Croissant Recheado com Ricota e Mel','Brunch',coalesce(25.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('CTHRAP','Croissant Herb Ricotta','Personalization',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('CTPCAP','Croissant Parma & Cheese','Personalization',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('CoffeeSyrup','Creme de Ricota doce com chocolate','Promo',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('Creme de Matcha','Creme de Matcha','Brunch',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('DRKSD1','Dark Soda','Limited Time',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('EGGBACAPP','Omelete Bacon','Brunch',coalesce(20.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('EMP','Empanada','Food',coalesce(11.5,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('EggWash','Egg wash doce','Promo',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('FBosButt','Farofa de Copa','Promo',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('FINC','Financier','Food',coalesce(12.5,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('FRUIT1','Fruit Salad','Fruit Salad',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('FRUSALAPP','Salada de Frutas','Brunch',coalesce(14.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('FSOD1','Fresh Soda - Limão Siciliano','Fresh Soda',coalesce(14.5,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('FSOD2','Fresh Soda - Pink Lemonade','Fresh Soda',coalesce(16.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('FSOD3','Fresh Soda - Kiwi','Fresh Soda',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('FSOD4','Fresh Soda - Maracujá','Fresh Soda',coalesce(14.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('FSOD5','Fresh Soda - Morango','Fresh Soda',coalesce(16.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('GHTOMAPP','Misto com Tomate Seco','Food',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('GOLLATAPP','Golden Latte','Limited Time',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('GRA30','Granola','Food',coalesce(7.5,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('GRABOLAPP','Granola Bowl','Brunch',coalesce(9.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('GRAFRUAPP','Yogurt Granola Bowl','Brunch',coalesce(25.5,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('Granola','Preparado de Granola','Promo',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('HOLECOAPP','Honey Lemon','Limited Time',coalesce(19.5,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('HONLATAPP','Honey Latte','Limited Time',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('HOSAMAAPP','Honey Salted Matcha','Limited Time',coalesce(18.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('ICECARAPP','Iced Salted Caramel','Signature',coalesce(17.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('ICECHOAPP','Iced Chocolat','Signature',coalesce(17.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('ICEGOLAPP','Iced Golden Latte','Limited Time',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('ICEMATCAPP','Iced Matcha Wild Vanilla','Signature',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('ICEMOCAPP','Iced Mocha','Signature',coalesce(18.5,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('ICEWILAPP','Iced Wild Vanilla','Signature',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('ICHCHOAPP','Ichigo Chocolat','Limited Time',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('JACHCAAPP','Fluffy Japanese cheesecake','Food',coalesce(21.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('JUI21','Orange, beetroot and carrot Juice 250ml','Other beverages',coalesce(14.5,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('JUI22','Green Juice 250ml','Other beverages',coalesce(14.5,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('JUI23','Orange Juice 250ml','Other beverages',coalesce(14.5,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('JUI24','Pineapple juice with mint 250ml','Other beverages',coalesce(14.5,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('JUI31','Orange Juice','Other beverages',coalesce(12.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('JUI32','Green Juice','Other beverages',coalesce(13.5,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('JUI33','Red Juice','Other beverages',coalesce(13.5,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('JUI41','Grape Juice','Other beverages',coalesce(15.5,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('KATSANAPP','Chicken Katsu Sando','Brunch',coalesce(29.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('KITCHRAPP','Kit de Natal 2024','Limited Time',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('KITEDIAPP','Kit Café Editions 750g - White, Kraft, Black','Promo',coalesce(169.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('KITWHIAPP','Kit Café 250g - 1kg','Promo',coalesce(169.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('MACCHIAPP','Macchiato','Purists',coalesce(11.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('MATCHL','Matcha Can 30g','Shop',coalesce(47.0,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('MATTONAPP','Matcha Tonic','Signature',coalesce(16.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('MATWILAPP','Matcha Wild Vanilla Latte','Signature',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('MCHAI','More Chai (36ml)','Personalization',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('MIXSOFTICE','Mixed Ice Cream','Desserts',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('MMAT','More Matcha (36ml)','Personalization',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('MOCOCAAPP','Verificar formação de preço','Personalization',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('MQ1','Misto Quente','Food',coalesce(16.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('MSOFTICE','Matcha Soft Ice Cream','Desserts',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('MUFCHOAPP','Muffin','Food',coalesce(13.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('MixEggs','Ovos Mexidos','Promo',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('MushShiSalt','Shitake Salteado Ref.','Promo',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('NUOAT','Veggie Milk Nude (barista edition)','Other beverages',coalesce(19.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('NUTICLAPP','Nutty Iced Latte','Limited Time',coalesce(18.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('NUTLATAPP','Nutty Latte','Limited Time',coalesce(15.5,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('ORECHAPP','Orenji Chai','Limited Time',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('PAFRMEAPP','Panqueca com Frutas e Mel','Brunch',coalesce(32.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('PASMATAPP','Passion Matcha','Limited Time',coalesce(18.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('PDQ11','Pão de Queijo','Food',coalesce(6.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('PDQ1CHAPP','Pão de Queijo com Requeijão','Food',coalesce(8.5,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('PDQSC1','Pão de Queijo Recheado','Food',coalesce(9.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('PrepBlue','Blue Preparad','Limited Time',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('PrepCacauBlack','Preparado Cacau Black','Limited Time',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('PrepChai','Chai Prepared','Limited Time',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('PrepChia','Preparado Pudim de Chia','Personalization',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('PrepChoco','Chocolat Sauce','Limited Time',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('PrepMatcha','Preparado de Matcha','Limited Time',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('PrepRagu','Preparado de Ragú','Brunch',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('PrepRoastBeef','Preparado de Roast Beef','Brunch',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('Preparado Panqueca','Preparado Panqueca','Brunch',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('QQ2','Queijo Quente','Food',coalesce(16.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('RAGSANAPP','Ragù Sandwich','Brunch',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('RMATCHA','Refill Matcha Sachet 30g','Shop',coalesce(33.0,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('ROBESAAPP','Roast Beef Sandwich','Brunch',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('RicottaChoco','Creme de Ricota doce com chocolate','Promo',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('RicottaSalt','Creme de Ricota salgado','Promo',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('RicottaSweet','Creme de Ricota doce','Promo',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('SALACOAPP','Salada de Acompanhamento (Brunch)','Personalization',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('SCUBANAPP','Cuban Sandwich','Brunch',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('SHAMEGGAPP','Ham and Eggs Special Sandwich','Brunch',coalesce(28.5,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('SHCH','Gelato Frappe Chocolate','Gelato Frappes',coalesce(21.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('SHCI','Gelato Frappe Chai','Gelato Frappes',coalesce(23.5,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('SHCO','Gelato Frappe Coffee','Gelato Frappes',coalesce(21.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('SHMA','Gelato Frappe Matcha','Gelato Frappes',coalesce(23.5,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('SHMO','Gelato Frappe Mocca','Gelato Frappes',coalesce(22.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('SHPT','Gelato Frappe Pistache','Gelato Frappes',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('SHSA','Gelato Frappe Salted Caramel','Gelato Frappes',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('SINSHOAPP','Pure Black (Single Shot)','Purists',coalesce(8.5,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('SLTC','Cookie Salted Caramel','Personalization',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('SMIXMUAPP','Peanut Butter & Shitake (veg) Sandwich','Brunch',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('SMUZBUFAPP','Mussarela de bufala e rúcula  Special Sandwich','Brunch',coalesce(34.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('SORICLAPP','Sora Iced Latte','Limited Time',coalesce(18.5,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('SORLATAPP','Sora Latte','Limited Time',coalesce(14.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('SPBJELAPP','Peanut Butter & Jam with bacon Sandwich','Brunch',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('TOAAVOAPP','Avocado Toast','Brunch',coalesce(34.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('TOABAEGAPP','Omelete Bacon Sandwich','Brunch',coalesce(27.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('TOABRIAPP','Brie, mel e amendoas Toast','Brunch',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('TOABUTAPP','Pão na Chapa com manteiga','Food',coalesce(11.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('TOACHOAPP','Chococream toast','Brunch',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('TOAFREAPP','French toast','Brunch',coalesce(29.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('TOAMATAPP','Matcha Toast','Brunch',coalesce(39.5,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('TOAMUSAPP','Shitake Toast','Brunch',coalesce(38.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('TOAOMEAPP','Omelete Toast','Brunch',coalesce(24.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('TOARICAPP','Geléia de Frutas Vermelhas Toast','Brunch',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('TOASALAPP','Salmão defumado Toast','Brunch',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('TOAST','Toast','Food',coalesce(11.5,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('TOATOMAPP','Tomate confit Toast','Brunch',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('TOBR12','Pão na Chapa','Food',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('TRANATAPP','Biscoito de Natal amanteigado','Limited Time',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('TestPrataGas','Sparkling Water Prata Glass 300ml','Other beverages',coalesce(12.5,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('TomConf','Tomate Confit Prep.','Promo',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('VSOFTICE','Vanilla Soft Ice Cream','Desserts',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('VinLem','Vinagrete de Limão','Promo',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('WATPRAAPP','Still Mineral Water Prata Glass 300ml','Other beverages',coalesce(12.5,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('WCRY3','Mineral Water Sparkling Water','Other beverages',coalesce(6.9,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('WFFC','Waffle','Food',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('WGAS','Water The Coffee  310ml Sparkling Water','Personalization',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('WILVANAPP','Wild Vanilla Latte','Signature',coalesce(15.5,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('WPIL','Mineral Water Sparkling WaterSilver Pilfer Glass 300ml','Other beverages',coalesce(12.5,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('WTHE','Water The Coffee  310ml','Other beverages',coalesce(null,0));
insert into produtos (sku_pdv,nome,categoria,preco_venda) values ('Water','Mineral Water without Gas','Other beverages',coalesce(null,0));

insert into fichas (produto_id,versao,rendimento,vigente_de) select id,1,1,current_date from produtos;

commit;
